# The base service is referenced in other projects.
base:
    build: .


dev:
    extends:
        service: base
    links:
        - postgres:rsadb
    volumes_from:
        - data
    entrypoint: []
    command: bash


web:
    extends:
        service: base
    links:
        - seed:seed
        - postgres:rsadb
    volumes_from:
        - data
    command: web


seed:
    extends:
        service: base
    # Hostname acts like a link to self
    hostname: seed
    volumes_from:
        - data
    command: seed 2552


master:
    extends:
        service: base
    links:
        - seed:seed
        - postgres:rsadb
    volumes_from:
        - data
    command: master


worker:
    extends:
        service: base
    links:
        - seed:seed
        - postgres:rsadb
    volumes_from:
        - data
    command: worker


data:
    build: .
    volumes:
        - ./src:/var/src/rsa/src
        - ./data:/var/src/rsa/data
        - ../config/rsa:/var/src/rsa/config
        - ./test-config:/var/src/rsa/test-config
        - ./.gradle-cache:/root/.gradle/caches
    entrypoint: []
    command: echo "RSA test data container"


# Version pegged; for a discussion about upgrading database versions see:
# http://stackoverflow.com/questions/40583196/if-i-upgrade-an-image-in-docker-compose-will-its-volumes-be-lost
postgres:
    image: postgres:9.6
