#!/usr/bin/env bash

EXECUTABLE=$0
if [ -L $0 ]; then
    # Dereference symbolic link so that libraries can be found. This is in case
    # the user has a link to this script from somewhere like ~/bin/rsa
    EXECUTABLE=$(readlink -f ${0})
fi
ROOTDIR=$(dirname ${EXECUTABLE})
echo $ROOTDIR

MAIN_JAR=$(ls -1 $ROOTDIR/rsaworkers*.jar | head -n1)
MAIN_CLASS="org.vpac.worker.Main"
CLASSPATH="${ROOTDIR}/resources:${MAIN_JAR}:${ROOTDIR}/lib/*"

# http://stackoverflow.com/questions/743454/space-in-java-command-line-arguments
echo java $JAVA_OPTS -classpath ${CLASSPATH} ${MAIN_CLASS} ${1+"$@"}
java $JAVA_OPTS -classpath ${CLASSPATH} ${MAIN_CLASS} ${1+"$@"}
